apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: traefik
subsets:
- addresses:
  - ip: 192.168.0.200
  ports:
  - port: 7777
- addresses:
  - ip: 192.168.0.201
  ports:
  - port: 7777
- addresses:
  - ip: 192.168.0.202
  ports:
  - port: 7777
- addresses:
  - ip: 192.168.0.203
  ports:
  - port: 7777

---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
  namespace: traefik
spec:
  ports:
  - port: 7777
